### ISSUE TITLE
Billing Dashboard: "Permission Denied, check project level permission."

### ISSUE THREAD

**Issue by twointum** [GoogleCloudPlatform/professional-services#1015]
Hello all, I am getting an error when running the setup for the billing dashboard. 

I am on step 4 here:
https://cloud.google.com/billing/docs/how-to/visualize-data

What permissions does the console need? Thank you!

**Comment by twointum** [comment]
Figured it out, needed to have both types of exports created. Close it!

**Comment by frankShih** [comment]
I have same issue.
I already export billing & billing_detail to BQ dataset.

Is there any possible solution?
