### ISSUE TITLE
Looker Studio Billboard template report is not publicly accessible

### ISSUE THREAD

**Issue by andyconlin** [GoogleCloudPlatform/professional-services#1073]
The method for visualizing GCP costs with Looker Studio (described in the tutorial [here](https://cloud.google.com/billing/docs/how-to/visualize-data)) encounters an error. I believe it's because the template report is no longer publicly accessible, therefore not able to be copied.

(template report is linked at the top of that tutorial as well as called out in the code [here](https://github.com/GoogleCloudPlatform/professional-services/blob/2f187cf833ecd4ebe03b36b60716810a708fa15d/examples/billboard/billboard.py#L27))

It seems the rest of the process described in the tutorial was successful. A new dataset was created and no errors were output in the terminal (iirc). When opening the URL provided at the end of the process, the following error message was given:

<img width="662" alt="image" src="https://github.com/GoogleCloudPlatform/professional-services/assets/24281063/776f37ac-456a-47d9-ab31-402ab04c463b">

Also, when attempting to access [the report](https://lookerstudio.google.com/c/reporting/64387229-05e0-4951-aa3f-e7349bbafc07/page/p_l3qef1s8rc) directly, this error is given:
> **Can't access report**
> Your current account myemailaddress@company.com can't access this report, or the report doesn't exist.

I've requested access via that error message (and am waiting on a response), but I don't imagine this report was meant to be blocked.

**Comment by greenozon** [comment]
as for today (3 Oct 2023) the link under "the report" in your post is visible and accessbile, eg:

![image](https://github.com/GoogleCloudPlatform/professional-services/assets/765343/11dbd9c9-742c-4dac-9476-98ca7a3f50df)

**Comment by andyconlin** [comment]
@greenozon thanks for sharing that. For me, this report still didn't give me access:
https://lookerstudio.google.com/reporting/64387229-05e0-4951-aa3f-e7349bbafc07
Then, when I realized that you were able to see it, it made me think that maybe it was a setting on my domain. That was it! There's a setting in Google Workspace admin for this. Not only do you set whether or not your internally-created assets can be shared elsewhere, but you have to specifically allow users to be able to access external Looker Studio assets.
