### ISSUE TITLE
Missing Dataflow python code - data_generation_for_benchmarking.py

### ISSUE THREAD

**Issue by rosera** [GoogleCloudPlatform/professional-services#133]
Hi - it looks like the file data_generation_for_benchmarking.py has been removed from the current master? This was previously available in "professional-services/examples/dataflow-python-examples/dataflow_python_examples"

I use this program in a datalflow example so if you could indicate if there is an alternative I can use - or whether I should even continue to use this example given the code has been deleted?

thanks

**Comment by igor-lakoza** [comment]
There is also a reference to this file in qwiklab lab "Simulating a Data Warehouse in the Cloud Using BigQuery and Dataflow"

**Comment by jaketf** [comment]
Hi rosera@ and igor-lakoza@,
Thank you for pointing this out. This code has been moved out of dataflow-python-examples to a top level example [dataflow-data-generator](https://github.com/GoogleCloudPlatform/professional-services/tree/master/examples/dataflow-data-generator). I will work on getting the qwiklab lab changed.

**Comment by rosera** [comment]
Hi, no worries. I have updated the qwiklabs exercise using already 😉
