### ISSUE TITLE
[Asset Inventory] Dataflow stalled (over 24h instead of 3h) on full CAI Ressource Dump

### ISSUE THREAD

**Issue by MarcFundenberger** [GoogleCloudPlatform/professional-services#1373]
We are using the tool "Asset Inventory" DataFlow Pipeline to load all of our Resources and IAM Rules in BigQuey Datasets.
Suddenly on the 18th of October 2024, the "resource" run of the DataFlow pipeline did not finish (we stopped it after more than 24h).  Prior to that date, typical running time was 3h.

The CAI dump is a full resource dump, meaning we do not specify any assetType to dump.

We tried removing the few new assetType  listed in CAI Release Notes from the list of assets found in CAI documentation.
That resulted in normal succesfull load, BUT the CAI Dump file is way smaller (60GiB instead of 70GiB for a dump), which indicates that we are missing some important assetTypes...

Is there any way to make sure that the Dataflow pipeline can handle a "full" CAI resource dump ?

**Comment by bmenasha** [comment]
Marc can you grant my google account (bmenasha@google.com) access to the CAI export that fails to be imported into BigQuery? 
thanks

**Comment by MarcFundenberger** [comment]
Done, you should have access to (both link to same file): 
https://storage.cloud.google.com/adeo-resource-inventory-dump-preprod/ExportAsset-2024-10-23.dump
gs://adeo-resource-inventory-dump-preprod/ExportAsset-2024-10-23.dump

**Comment by MarcFundenberger** [comment]
From additional tests, it seems that the culprit is the "cloudbuild.googleapis.com/Build" asset type.
In a "full" resource dump, I have over 1.6 million of such assets.
AFAIK, there is not mention of such an asset type in the Cloud Asset Inventory documentation or release Notes...

**Comment by bmenasha** [comment]
this pull request should resolve it. https://github.com/GoogleCloudPlatform/professional-services/pull/1394    
I'll update the latest pipeline after it's merged. 

thanks

**Comment by bmenasha** [comment]
change is merged. dataflow template was updated. let me know if there are any problems. 
thanks

**Comment by MarcFundenberger** [comment]
Thanks for the update.
I'll try a "full" dump including the problematic resource and I'll let you know how it went.

**Comment by MarcFundenberger** [comment]
Allright, the problematic asset type is successfully loaded with the new pipeline version, thank you !
