### ISSUE TITLE
[Asset Inventory] Dataflow pipeline is using an deprecated SDK version (2.41.0)

### ISSUE THREAD

**Issue by MarcFundenberger** [GoogleCloudPlatform/professional-services#1374]
The GCP Dataflow console is alerting us that the Dataflow SDK version used by the Asset Inventory tool is deprecated (2.41.0).
Can you please modify the template to use an up-to-date SDK ?

**Comment by bmenasha** [comment]
this pull request should resolve it. https://github.com/GoogleCloudPlatform/professional-services/pull/1394    
I'll update the latest pipeline after it's merged. 
thanks

**Comment by bmenasha** [comment]
change is merged. dataflow template was updated. let me know if there are any problems.
thanks

**Comment by MarcFundenberger** [comment]
Hello
Thanks for your work. Pipeline is working as intended.
However the column resource.json_data changed type from STRING to JSON with the new pipeline.
I agree it's better this way but it has the unforeseen consequence that you can't query it on dates that where generated with the old and new version of the pipeline...
E.g. : 
```
select resource.json_data from `dfdp-sre-data.shardedAdeoAssetInventory.container_googleapis_com_Cluster_202411*`
```
Crashed with error `Cannot read field of type STRING as JSON Field: resource.json_data`
But the column resource.json_data holds the same data than the rest of the column, so it's basically redundant... 
Anyway,  think it's bad practice to use our inventory Dataset this way, so I'll educate our users that try this (and complain) .

Perhaps next time we could work out a way for us tho test a pre-release version of the pipeline ? 

Thanks again.

**Comment by bmenasha** [comment]
Yes, this was a backwards incompatible change.  When this code was originally written, BigQuery didn't have a JSON datatype.   Honestly if the JSON datatype existed back then I doubt we would have written this tool :) 

> Perhaps next time we could work out a way for us tho test a pre-release version of the pipeline ?

The Dataflow template  gs://professional-services-tools-asset-inventory/test/import_pipeline  is typically updated prior to the latest Dataflow template if you want to get changes sooner. 

> so it's basically redundant...

There are situations where the BigQuery schema can't represent the data,  for example when the bigquery column count is exceeded, the depth of the nested records exceeds bigquery's limits, the column name is too long.  We just truncate the data in such cases, but I didn't want to lose the original data in that event.

**Comment by MarcFundenberger** [comment]
> We just truncate the data in such cases, but I didn't want to lose the original data in that event.

Yes, you're right, of course.
Thank you for your answers.
