### ISSUE TITLE
Live example link broken

### ISSUE THREAD

**Issue by t4r4d4ctyl** [GoogleCloudPlatform/professional-services#192]
Can't access this URL:
https://storage.googleapis.com/strike3-gcp-arch-viz/gcp-arch-viz.html

Originally found in this public article as well:
https://medium.com/google-cloud/visualize-gcp-architecture-using-forseti-2-0-and-d3-js-ffc8fdf59450

Seems like great work. Thanks for sharing.

**Comment by mzinni** [comment]
Thanks for reporting!

Yep, I accidentally deleted the GCS bucket (and these files) when I firebombed personal projects that were costing $$. Just recreated another bucket, added files back in, and edited medium.com article to reflect new URL(s). 
https://storage.googleapis.com/forsetiviz-external/gcp-arch-viz.html

PR to fix README.md coming shortly...
