### ISSUE TITLE
Error using Cloud Asset Inventory Import To BigQuery

### ISSUE THREAD

**Issue by hot1989hot** [GoogleCloudPlatform/professional-services#218]
At Step 11 in quick start, 

`gcloud dataflow jobs run $JOB_NAME  --gcs-location gs://professional-services-tools-asset-inventory/latest/import_pipeline --parameters="input=$BUCKET/*.json,stage=$BUCKET/stage,load_time=$LOAD_TIME,group_by=ASSET_TYPE,dataset=asset_inventory,write_disposition=WRITE_APPEND" --staging-location $BUCKET/staging
`

After Running this command, the dataflow console gives me these errors:

>  Autoscaling is enabled for job 2019-03-19_15_09_01-12592583255883649300. The number of workers will be between 1 and 1000. 

>  Autoscaling was automatically enabled for job 2019-03-19_15_09_01-12592583255883649300. 

>  Checking permissions granted to controller Service Account. 

>  Staged package apache_beam-2.9.0-cp27-cp27mu-manylinux1_x86_64.whl at location 'gs://professional-services-tools-asset-inventory/export_resources_staging_location/beamapp-bmenasha-0316165513-832710.1552755313.832831/apache_beam-2.9.0-cp27-cp27mu-manylinux1_x86_64.whl' is inaccessible.

>  **Staged package dataflow_python_sdk.tar at location 'gs://professional-services-tools-asset-inventory/export_resources_staging_location/beamapp-bmenasha-0316165513-832710.1552755313.832831/dataflow_python_sdk.tar' is inaccessible.** 

>  **Staged package pickled_main_session at location 'gs://professional-services-tools-asset-inventory/export_resources_staging_location/beamapp-bmenasha-0316165513-832710.1552755313.832831/pickled_main_session' is inaccessible.** 

>  **Staged package workflow.tar.gz at location 'gs://professional-services-tools-asset-inventory/export_resources_staging_location/beamapp-bmenasha-0316165513-832710.1552755313.832831/workflow.tar.gz' is inaccessible.** 

>  **Workflow failed. Causes: One or more access checks for temp location or staged files failed. Please refer to other error messages for details. For more information on security and permissions, please see https://cloud.google.com/dataflow/security-and-permissions.**

>  Cleaning up. 

>  Worker pool stopped.

**Comment by bmenasha** [comment]
Very sorry. This issue is now corrected. 
Thanks for tying out the project.

**Comment by bmenasha** [comment]
Please reopen if you encounter any problem.
thanks
