### ISSUE TITLE
 Asset Inventory tool : Permission denied to template file 

### ISSUE THREAD

**Issue by varelasavela** [GoogleCloudPlatform/professional-services#239]
Hey guys,
I am trying to run Asset Inventory tool and my service account which I use can't get the template file getting error:
Template file failed to load: gs://professional-services-tools-asset-inventory/latest/import_pipeline. Permissions denied. <my-account>@appspot.gserviceaccount.com does not have storage.objects.get access to professional-services-tools-asset-inventory/latest/import_pipeline

Should I create add upload the template by myself?

**Comment by bmenasha** [comment]
Sorry for the trouble varelasavela@ I just changed the permisisons on the template file a few hours ago to be public.

**Comment by bmenasha** [comment]
Let me know if the problem is still occurring.
