### ISSUE TITLE
Asset Inventory tool : error during pipeline running

### ISSUE THREAD

**Issue by varelasavela** [GoogleCloudPlatform/professional-services#241]
Hi guys
I am using the Asset Inventory tool and I got an error during pipeline running:
ImportError: No module named asset_inventory.api_schema
I tried to use save_main_session = True option but it didn't help.

What am I doing wrong?

Thx

**Comment by jaketf** [comment]
@bmenasha can you take a look at this?

**Comment by bmenasha** [comment]
I'm not sure. Can you share the full command line you used to invoke the template, or was this via the GAE app? 

thanks

**Comment by varelasavela** [comment]
GAE app invoked the template.
I build the template from import_pipeline.py by 
python -m import_pipeline --runner=DataflowRunner --project=<project_id> --staging_location gs://<org>-assets/staging --temp_location gs://<org>-assets/temp --template_location gs://<prg>-assets/templates/mytemplate
and changed the config.yaml to invoke my template

**Comment by varelasavela** [comment]
I had to add setup_file parameter in order to fix this issue
