### ISSUE TITLE
Asset Inventory tool : pipeline failed on one of the last steps

### ISSUE THREAD

**Issue by varelasavela** [GoogleCloudPlatform/professional-services#243]
Hi guys

After I got the view permissions on gs://professional-services-tools-asset-inventory/latest/import_pipeline template, I managed to run it via GAE app.
But it still failed. You can see the screenshot 👍 
![Screen Shot 2019-04-30 at 13 18 39](https://user-images.githubusercontent.com/7138845/56955621-9995e400-6b4a-11e9-8231-bd512831246c.png)

In the pipeline options I see parameters which I guess I have to be able to change them.
![Screen Shot 2019-04-30 at 13 21 13](https://user-images.githubusercontent.com/7138845/56955722-dbbf2580-6b4a-11e9-8de6-386b853da7fb.png)

For example temp_location, staging_location, project (bmenasha-1) 
How can I change them and can it be the issue why the pipeline got failed ?

Thx

**Comment by varelasavela** [comment]
I noticed that pipeline always stuck during "group_assets_by_key" step after 56 elements processed (I can see the output jsons in the bucket) . 
also I can see in the logs "Refusing to split GroupedShuffleRangeTracker proposed split position is out of range" that means that job is stuck doing something non-parallelizable on a small number of workers, while other workers are staying idle. I guess that it is because one of the ASSET_TYPE (it's a key of GroupBy ) has a lot of values

**Comment by bmenasha** [comment]
varelasavela..  Can you try limiting the number of workers to just one?

"maxWorkers": 1

in import_pipeline_runtime_environment, perhaps something is going wrong with the Dataflow shuffler or my import pipeline code is bad.

I hope we can get the import to work if you try setting  "import_group_by: NONE" but this will just give you the single "resources" json table and not BigQuery tables broken out by asset type.  


 Can you give me your project id and permission to look at your logs?  or even better give me access to the json files you are importing so I can recreate by copying them to a bucket and giving my account read access (bmenasha@google.com) to it?

I don't think it's the temp_location or staging_location is the problem as then the Dataflow job would have failed much earlier.    

Thanks

**Comment by varelasavela** [comment]
@bmenasha 
Project id is doitintl-asset-inventory
I grant you the permissions. If something is missing please let me know.
As you said I agree that temp_location or staging_location is not the problem.
The problem is in GroupBy action in group_assets_by_key step, I guess one of the groups is huge and it goes to the single worker which can't handle it.

**Comment by varelasavela** [comment]
@bmenasha 
I tried to run it with only 1 worker and it still stuck and failed after.

**Comment by bmenasha** [comment]
Thanks varelasavela , I have a fix I'm testing now.   I was able to load your file with it in 2 hours and I think with another small change I can get this down even further. I'll get back to you tonight.

**Comment by bmenasha** [comment]
@varelasavela  

With these two commits in  pull/237 I was able to process the export in 30 minutes

https://github.com/GoogleCloudPlatform/professional-services/pull/237/commits/9d7a2267a05c5503d65dfb122324182a35780c15
https://github.com/GoogleCloudPlatform/professional-services/pull/237/commits/11c8c780102091992d081b10a242d4a8b2d70e68

The template at gs://professional-services-tools-asset-inventory/latest/import_pipeline  is already updated with these changes. 

The  file contains a large number of BigQuery tables, to processes them quicker I added the ability to shard each asset type a configurable number of times with the "num_shards" pipeline parameter. You can set it with the "import_num_shards"  configuration in the gae/config.yaml once the pull request is merged. 

To get to 30 minutes I ran with two changes, first chaging input_num_shares to:

import_num_shards: *=1,resource=100,google.cloud.bigquery.Table=100

Then enabling the  Dataflow Shuffler with     "additionalExperiments": ["shuffle_mode=service"] in the import_pipeline_runtime_environment:

import_pipeline_runtime_environment: >
  {
    "tempLocation": "gs://bmenasha-1-test-bucket/dataflow_temp",
    "additionalExperiments": ["shuffle_mode=service"]
  }

Thanks for trying, let me know if it works for you.

**Comment by varelasavela** [comment]
@bmenasha 
Hi,
I tried to executed your new template with the code changes which you did and I got the following error (The template parameters are invalid).
![Screen Shot 2019-05-01 at 14 54 22](https://user-images.githubusercontent.com/7138845/57016144-39be3c80-6c21-11e9-93e0-4281913cdc18.png)

Any ideas what could be a problem?
Thanks for help

**Comment by bmenasha** [comment]
@varelasavela  my fault. I corrected it in 

https://github.com/GoogleCloudPlatform/professional-services/pull/237/commits/fe8be9ffbf0cf432f562960628c49b0544b76b70

and updated the template. 

You should just be able to run again. 
thanks

**Comment by varelasavela** [comment]
@bmenasha 
Thanks
It worked
