### ISSUE TITLE
Unable to generate and publish mqtt

### ISSUE THREAD

**Issue by aleonnet** [GoogleCloudPlatform/professional-services#250]
I'd like to offer a feedback I did not have to other users.

As I've run it in Python 3, I had to explicitly convert the iterator into a sequence (list, tuple, etc) to allow unpack it multiple times

-----------------------
Hi @lerrytang ,
I'm unable to generate/publish mqtt payload when running locally EnergyDisaggregationDemo_Client.ipynb even though no error message is produced.

Would you help me please? What can I do to make it work?

http://localhost:8890/notebooks/EnergyDisaggregationDemo_Client.ipynb#
------------
before data trimming: data.shape=(432000,)
after data trimming: data.shape=(131820,)
Creating JWT using RS256 from private key file rs256.key
connected: Connection Accepted.
connected: Connection Accepted.
connected: Connection Accepted.
...

![image](https://user-images.githubusercontent.com/20618327/57588745-34010a80-74ef-11e9-8e74-8248b4d00592.png)

**Comment by aleonnet** [comment]
I'd like to offer a feedback I did not have to other users.

As I've run it in Python 3, I had to explicitly convert the iterator into a sequence (list, tuple, etc) to allow unpack it multiple times

**Comment by lerrytang** [comment]
Hi @aleonnet 

Thanks for being interested in our demo, and I'm sorry for the late reply.
Yes, our demo was written in python 2.7.

Don't hesitate to contact us should there be any further problems.

Regards,
