### ISSUE TITLE
Publish gsuite-exporter pypi so that pip install command works

### ISSUE THREAD

**Issue by andrey-snowflake** [GoogleCloudPlatform/professional-services#282]
The pip install command on [this readme](https://github.com/GoogleCloudPlatform/professional-services/tree/master/tools/gsuite-exporter) does not work —

    $ pip install gsuite-exporter
    Collecting gsuite-exporter
      ERROR: Could not find a version that satisfies the requirement gsuite-exporter (from versions: none)
    ERROR: No matching distribution found for gsuite-exporter

I think this is because the author intended to publish this to pypi but never did?

https://pypi.org/search/?q=gsuite

**Comment by teambob** [comment]
It seems to work for Python2 but not Python3

**Comment by ocervell** [comment]
@andrey-snowflake sorry for the delay here. The package has now been published on PyPI !

**Comment by andrey-snowflake** [comment]
thank you kindly!
