### ISSUE TITLE
BQ Visualizer Subdirectories are missing after refactor/move of components

### ISSUE THREAD

**Issue by janpeuker** [GoogleCloudPlatform/professional-services#294]
Raising this as a sample Beginner issue

**Comment by tims** [comment]
Can't seem to add @smeyn as assignee

**Comment by smeyn** [comment]
However for some reason that comment ended up in my private email

**Comment by johnxavier11** [comment]
i did my gcp code here for my youtube link for my devops classe

**Comment by agold-rh** [comment]
Closed due to inactivity.
