### ISSUE TITLE
Asset inventory issue

### ISSUE THREAD

**Issue by leone145** [GoogleCloudPlatform/professional-services#318]
Running into duplicate key entries at the Big Query level when utilizing the asset inventory app engine via dataflow template.

`[root@jump01 asset_inventory]# bq show -j <jobid>
Job project1:<jobid>

  Job Type    State      Start Time         Duration                                  User Email                               Bytes Processed   Bytes Billed   Billing Tier   Labels
 ---------- --------- ----------------- ---------------- -------------------------------------------------------------------- ----------------- -------------- -------------- --------
  load       FAILURE   16 Sep 18:57:16   0:00:00.633000   viewer@project1.iam.gserviceaccount.com

Error encountered during job execution:
Error while reading data, error message: JSON table encountered too many errors, giving up. Rows: 1; errors: 1. Please look into the errors[] collection for more details.
Failure details:
 - Error while reading data, error message: JSON processing
   encountered too many errors, giving up. Rows: 1; errors: 1; max
   bad: 0; error percent: 0
 - gs://<orgid>-assets/stage/2019-09-16T22:48:25.550864/compute.g
   oogleapis.com/GlobalForwardingRule.0.json: Error while reading
   data, error message: JSON parsing error in row starting at position
   0: Multiple definition of field: resource.data.ipProtocol
`

**Comment by leone145** [comment]
Adding the code below to cai_to_api_properties.json appears to have resolved issue. Will update further once the app engine is updated and the code runs fully. So far only tested with direct CLI run.


    "GlobalForwardingRule": {
        "cai_to_api_names": {
            "ipAddress": "IPAddress",
            "ipProtocol": "IPProtocol"
        }
    },

**Comment by leone145** [comment]
After re-generating the import_pipeline file, the dataflow template job has been successful

**Comment by gkowalski-google** [comment]
[Here is a link to the announcement that documents the updated field names](https://cloud.google.com/resource-manager/docs/cloud-asset-inventory/naming-table).

**Comment by bmenasha** [comment]
Thanks for the information. I'm in meeting all day but will take a loot at this and hopefully have a fix with an updated pipeline deployed tomorrow.

**Comment by bmenasha** [comment]
Pull request #321 should fix this, I've already updated the pipeline template.
thanks
