### ISSUE TITLE
passing num_shard parameter and enabling Dataflow Shuffler with command line approach 

### ISSUE THREAD

**Issue by Parasdogra** [GoogleCloudPlatform/professional-services#333]
Can you please update the documentation to pass num_shard parameter and enable dataflow shuffler using command line approach. 

passing the parameter num_shards: *=1,resource=100,google.cloud.bigquery.Table=100 in 
gcloud dataflow jobs run command

**Comment by bmenasha** [comment]
this issue has been fixed with the merge of the pull request. but i'm not able to mark it as fixed.
