### ISSUE TITLE
Fix vulnerabilities in bq-visualizer

### ISSUE THREAD

**Issue by AdrienWalkowiak** [GoogleCloudPlatform/professional-services#342]
gts init -y returns the following for bq-visualizer:

audited 43161 packages in 12.274s
found 616 vulnerabilities (1 low, 1 moderate, 612 high, 2 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

Please update your packages to fix the vulnerabilities.

**Comment by jaketf** [comment]
@smeyn PTAL

**Comment by agold-rh** [comment]
Closed due to inactivity.
