### ISSUE TITLE
Fix data-analytics/iot-nirvana/client/pom.xml

### ISSUE THREAD

**Issue by AdrienWalkowiak** [GoogleCloudPlatform/professional-services#343]
There is a vulnerability in org.eclipse.paho:org.eclipse.paho.client.mqttv3. 

The proposed remediation is:
Upgrade org.eclipse.paho:org.eclipse.paho.client.mqttv3 to version 1.2.1 or later. 

also, please lint your java files using [google-java-format](https://github.com/google/google-java-format). 

You can use:

`java -jar /usr/share/java/google-java-format-1.7-all-deps.jar -r my-file.java
`

on each java file to lint your code according to Google guidelines for java.

**Comment by morgante** [comment]
@dan-anghel Can you PTAL?

**Comment by agold-rh** [comment]
Closed due to inactivity.
