### ISSUE TITLE
direct-upload-to-gcs example not working

### ISSUE THREAD

**Issue by mopoppe** [GoogleCloudPlatform/professional-services#365]
I've successfully deployed the direct-upload-to-gcs, however I am getting a '404 page not found' error from the service when I try to create a signed url.   Are the steps provided in the example complete?

**Comment by mhugues** [comment]
did you try to set the appengine url in the go code example suffix with /sign ?

**Comment by mopoppe** [comment]
Thank you. That seemed to help as I see it's trying to sign now but returning an error.  

$ go run upload.go
Signed URL here: "failed to sign by internal server error"
2019/12/09 10:55:38 Put failed%20to%20sign%20by%20internal%20server%20error: unsupported protocol scheme ""
exit status 1

A few questions...
1. How would I know i need to have /sign appended to the appengine url?
2. Unsupported protocol scheme usually means I'm missing "https://" but that is not the case:

const signerUrl = "https://ddn-customer-support-portal.appspot.com/sign"

**Comment by mopoppe** [comment]
For my second question I see that the issue really is that I'm getting a signing failure. Will look into seeing what is causing that.

**Comment by mopoppe** [comment]
Seeing this in the logs: "2019/12/09 17:08:35 upload: unsupported MIME type, got = "application/octet-stream""

**Comment by mopoppe** [comment]
It's definitely trying to upload the png file that I've created, and it's a png as well:

DDN11721M:upload mpoppe$ mv sample.png badsample.png
DDN11721M:upload mpoppe$ go run upload.go
Signed URL here: "failed to sign by internal server error"
2019/12/09 12:16:29 open ./sample.png: no such file or directory
exit status 1
DDN11721M:upload mpoppe$ mv badsample.png sample.png
DDN11721M:upload mpoppe$ file sample.png
sample.png: PNG image data, 45 x 45, 8-bit colormap, non-interlaced
DDN11721M:upload mpoppe$ go run upload.go
Signed URL here: "failed to sign by internal server error"
2019/12/09 12:18:16 Put failed%20to%20sign%20by%20internal%20server%20error: unsupported protocol scheme ""
exit status 1

**Comment by mopoppe** [comment]
Not sure that the unsupported MIME type is the actual issue... the logs viewer seems to either have a delay before they show, or the timestamp is off.  What I see in there doesn't seem to align with what I am doing with the application.

**Comment by mhugues** [comment]
The appengine service should have the service account token creator role
