### ISSUE TITLE
Asset inventory issue : load failed due to TIMESTAMP to STRING change ???

### ISSUE THREAD

**Issue by jf-marquis-Adeo** [GoogleCloudPlatform/professional-services#367]
Hi there,
Cloud Dataflow job is failing due to this error:
sqladmin_googleapis_com_Instance. Field resource.data.scheduledMaintenance.startTime has changed type from TIMESTAMP to STRING [while running 'load_to_bigquery/load_to_bigquery']
this occurs on:
- sqladmin_googleapis_com_Instance
- compute_googleapis_com_RegionBackendService.
- k8s_io_Pod
- ...
What can i do to correct ?
Thanks a lot for your help

**Comment by bmenasha** [comment]
Marquis, we made a backwards incompatible change to the BigQuery schema we import asset inventory to with PR#  344.    https://github.com/GoogleCloudPlatform/professional-services/pull/344

You can correct the issue by just deleting the dataset and creating it again hopefully the old exports aren't important for you to keep. Alternatively you can change the --write_disposition to WRITE_EMPTY so tables are deleted first prior to import of the new data. 
thanks

**Comment by jf-marquis-Adeo** [comment]
ok thanks
