### ISSUE TITLE
gke redis-cluster deployment error.

### ISSUE THREAD

**Issue by cartagon-tec** [GoogleCloudPlatform/professional-services#393]
Hi.

Thanks for the article about gke cluster-redis, is very interesting.

I realize the configration and when y tray to test it, i have the next error.

kubectl get pods -l app=redis,redis-type=cache -o wide
NAME                           READY   STATUS    RESTARTS   AGE     IP          NODE                                        NOMINATED NODE   READI
NESS GATES
redis-cache-64f4d98457-7lph9   1/1     Running   0          19m     10.0.1.34   gke-dev-ironia-pruebas-d1d66cb9-d9q7        <none>           <none
>
redis-cache-64f4d98457-bkwx4   1/1     Running   0          6m58s   10.0.1.27   gke-dev-ironia-default-pool-1f34a49a-nc7b   <none>           <none
>
avalencia@cloudshell:~/redis/professional-services/examples/redis-cluster-gke$ kubectl run -it redis-cli --image=redis --restart=Never /bin/bash
If you don't see a command prompt, try pressing enter.
root@redis-cli:/data# redis-cli -c -p 6379 -h 10.0.1.34
10.0.1.34:6379> set foo bar
**(error) CLUSTERDOWN Hash slot not served**
10.0.1.34:6379>

Any idea about the problem?

Thanks in advance

**Comment by haroldjcastillo** [comment]
I have the issue, @cartagon-tec have you ever solved ?

**Comment by agold-rh** [comment]
Closed due to inactivity.
