### ISSUE TITLE
LOG_EXPORT_NAME for DLP & Cloud Function example

### ISSUE THREAD

**Issue by jasonbisson** [GoogleCloudPlatform/professional-services#406]
The variable for LOG_EXPORT_NAME is not defined in the readme which causes the Log export command to fail.

https://github.com/GoogleCloudPlatform/professional-services/tree/master/examples/dlp/cloud_function_example

**Comment by agold-rh** [comment]
@jaketf @adelanre @matthewmarr Do you have any input, or should this be closed as stale?

**Comment by agold-rh** [comment]
Closed due to inactivity.
