### ISSUE TITLE
estimatedCostUsd in BQ Audit doesn't reflect BQ ML charges accurately

### ISSUE THREAD

**Issue by slachterman-g** [GoogleCloudPlatform/professional-services#421]
BQ ML CREATE MODEL queries are billed at $250 per model, per https://cloud.google.com/bigquery-ml/pricing

Since BQ ML SQL will appear in the SQL file, we should ensure that the estimated costs for the create model statements are reflected accurately

**Comment by agold-rh** [comment]
Closed due to inactivity.
