### ISSUE TITLE
Asset inventory - update to python 3 and RFI

### ISSUE THREAD

**Issue by jf-marquis-Adeo** [GoogleCloudPlatform/professional-services#423]
Hello
the dataflow pipeline seems to be in python 2.7 which is deprecated. Is it possible to update it to python 3, please?
In your code, you're linking a dict that is not accessible ( # https://colab.corp.google.com/drive/183eM8uKO0V-HD2ldx7AMJ8H6UQnh3JHt). Is it possible to provide it, please?
Thanks a lot for these tools which is very useful for us.
Have a nice day
best regards

**Comment by jaketf** [comment]
@bmenasha PTAL this.
I've had some success w/ [2to3 tool](https://docs.python.org/2/library/2to3.html) for updating other assets in this repo.

**Comment by bmenasha** [comment]
Thanks for the issue report. Merging #425 will resolve this issue.  There is no longer a need to maintain the cai_to_api module and that commit removes the whole module. The code has always supported python 3 and this change makes it more clear and i've also updated the production dataflow template to run in python 3. 
thanks
