### ISSUE TITLE
Add flake8 to CI tool to catch python errors sooner

### ISSUE THREAD

**Issue by jaketf** [GoogleCloudPlatform/professional-services#443]
This repo has a lot of issues w/ consistency and while some.
This will likely be a heavy lift at first but will pay dividends in the long run as the repo grows.

Let's add some more static checks:
- flake8 
- shellcheck

Let's find a way to automate running the tests in cloud build for new assets.

**Comment by dandynaufaldi** [comment]
maybe starts with which warning/error codes are allowed from [PyFlakes](http://flake8.pycqa.org/en/2.5.5/warnings.html) and [pep8](https://pep8.readthedocs.io/en/latest/intro.html#error-codes) to specify arguments for running flake8

then we can start modify:
- [Dockerfile](https://github.com/GoogleCloudPlatform/professional-services/blob/master/cloudbuild/Dockerfile) to install dependencies like flake8 and shellcheck
- [format.sh](https://github.com/GoogleCloudPlatform/professional-services/blob/master/helpers/format.sh) to help format and lint code while developing
- [check_format.sh](https://github.com/GoogleCloudPlatform/professional-services/blob/master/helpers/check_format.sh) for checking in CI pipeline

we may also need to re-check the [exclusion](https://github.com/GoogleCloudPlatform/professional-services/blob/master/helpers/exclusion_list.txt). Also want to ask why did we have an exclusion list in the first place?

**Comment by dandynaufaldi** [comment]
flake8 statistics on `examples` directory without select/ignore specific error/warning
```
1234  E111 indentation is not a multiple of four
103   E114 indentation is not a multiple of four (comment)
9     E122 continuation line missing indentation or outdented
8     E124 closing bracket does not match visual indentation
3     E125 continuation line with same indent as next logical line
18    E127 continuation line over-indented for visual indent
42    E128 continuation line under-indented for visual indent
2     E129 visually indented line with same indent as next logical line
5     E131 continuation line unaligned for hanging indent
7     E231 missing whitespace after ','
4     E251 unexpected spaces around keyword / parameter equals
5     E261 at least two spaces before inline comment
69    E265 block comment should start with '# '
2     E301 expected 1 blank line, found 0
8     E302 expected 2 blank lines, found 1
14    E303 too many blank lines (2)
11    E305 expected 2 blank lines after class or function definition, found 1
1     E306 expected 1 blank line before a nested definition, found 0
1     E402 module level import not at top of file
445   E501 line too long (80 > 79 characters)
5     E712 comparison to False should be 'if cond is False:' or 'if not cond:'
3     E722 do not use bare 'except'
3     E731 do not assign a lambda expression, use a def
1     E741 ambiguous variable name 'l'
4     E999 SyntaxError: invalid syntax
37    F401 'datetime.datetime' imported but unused
1     F403 'from my_module.my_module import *' used; unable to detect undefined names
22    F405 'is_numeric' may be undefined, or defined from star imports: my_module.my_module
3     F821 undefined name 'key_cols'
22    F841 local variable 'start_time' is assigned to but never used
103   W291 trailing whitespace
4     W292 no newline at end of file
14    W293 blank line contains whitespace
10    W391 blank line at end of file
17    W605 invalid escape sequence '\d' 
```

**Comment by morgante** [comment]
For some context, we originally added the exclusion list to make it possible to incrementally add CI and standards without having to do massive PR.

We should certainly be trying to incrementally remove exclusions over time, but it should be easier to fix one tool at a time with small PRs.

**Comment by jaketf** [comment]
I think proof is in the pudding that no one is updating their assets out of exclusion list.
Also I think even stuff that is not in exclusion list has flake8 issues.
I think adding flake8 and a massive PR to fix broken assets will make us avoid a lot of these issues in the future.

**Comment by morgante** [comment]
> I think proof is in the pudding that no one is updating their assets out of exclusion list.

Yeah that's likely something we'll either have to mandate or take on ourselves to get any traction with. At the very least, it should make for smaller PRs though.
