### ISSUE TITLE
Limit Flake8 checks only to logical errors 

### ISSUE THREAD

**Issue by prathapreddy123** [GoogleCloudPlatform/professional-services#468]
@jaketf , @tswast 

Since yapf is used primarily for formatting, to avoid spending time over flake8 style issues (flake8 uses pycodestyle checks) such as whitespace, continuation line unaligned etc can we restrict the Flake8 to check only for pyflake errors (https://flake8.pycqa.org/en/latest/user/error-codes.html#error-violation-codes).  

Recommended fix is to change https://github.com/GoogleCloudPlatform/professional-services/blob/master/helpers/check_format.sh#L48 as follows:

flake8 --exclude=.git,__pycache__,.venv,venv --select=E9,F

**Comment by tswast** [comment]
Hmmm... With `black`, there only a few rule exceptions that need to be made https://github.com/googleapis/synthtool/blob/master/synthtool/gcp/templates/python_library/.flake8

I'd prefer we exclude certain rules rather than include them.

If this can't be done with `yapf`, then I suggest we switch to `black`.

**Comment by tswast** [comment]
Also, you've got a lot of directories that are excluding from `yapf` formatting. https://github.com/GoogleCloudPlatform/professional-services/blob/master/helpers/exclusion_list.txt These would need to be cleaned up if there is significantly fewer checks done by flake8.

**Comment by prathapreddy123** [comment]
Thanks @tswast.  My thoughts are:

1. As  yapf supports Google Style convention and is widely used within Google as well as supports auto formatting , we can continue using yapf for style based checks.

2. Flake8 can be limited to Logic related checks which are grouped under F related codes. 
    Same conventions followed in [beam SDK](https://github.com/apache/beam/blob/master/sdks/python/scripts/run_pylint.sh#L77) as well: 
     

Goal is to avoid style conflicts between yapf and Flake8 tools and also should discourage adding new projects to exclusions list

**Comment by tswast** [comment]
Probably makes sense to follow the Beam SDK convention in that case.

**Comment by prathapreddy123** [comment]
Fixed the issue via [PR](https://github.com/GoogleCloudPlatform/professional-services/pull/476)
