### ISSUE TITLE
test: typescript formatter not actually used

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/professional-services#479]
As far as I can tell `./examples/ml-audio-content-profiling` is the only sample that has typescript, but it's in the exclusions list.

I believe it's being excluded because it takes forever to run some of the other formatters against it due to the `node_modules` directory. I think we'll need to make sure we exclude that from any formatting.

**Comment by morgante** [comment]
It doesn't look like that example has any node_modules currently committed so I'm not sure why that's delaying tests?

In general, we should probably exclude any directories listed in `.gitignore`.

**Comment by tswast** [comment]
When `npm audit` is run, it creates the `node_modules` directory, delaying other tests.

> In general, we should probably exclude any directories listed in .gitignore.

That's a good idea.

**Comment by agold-rh** [comment]
Closed due to inactivity.
