### ISSUE TITLE
GCP Architecture Visualizer example not working

### ISSUE THREAD

**Issue by AndrejGajdos** [GoogleCloudPlatform/professional-services#482]
GCP Architecture Visualizer example is [not working](https://storage.googleapis.com/forsetiviz-external/gcp-arch-viz.html).

**Comment by ryanmcdowell** [comment]
Unfortunately this tool is no longer maintained in this repository as it's been pulled into Forseti. I've created #484 to address this.

https://cloud.google.com/blog/products/identity-security/understand-gcp-organization-resource-hierarchies-with-forseti-visualizer
