### ISSUE TITLE
[slo-generator] Issue when NoData with good_bad_ratio method

### ISSUE THREAD

**Issue by bkamin29** [GoogleCloudPlatform/professional-services#497]
Hello,

When using `good_bad_ratio`, what happens if one of my two filter `filter_good` or `filter_bad` have No data available ?
For exemple if my service have no problems, `filter_good` have data but not `filter_bad`.
In this case and since the latest version of `slo-generator`, no SLI results are computed and sent to Bigquery..

In my exemple i use this log-based-metric :

```
resource "google_logging_metric" "quality_count" {
  name        = "nfs/quality_count"
  description = "Metric based on logs provided by the Cypress Cronjob. Used to compute quality SLO on NFS"
  filter      = "resource.type=\"k8s_container\"\nresource.labels.container_name=\"crj-sre-homepage-fr\"\njsonPayload.country=\"fr\""
  metric_descriptor {
    metric_kind = "DELTA"
    value_type  = "INT64"
    unit        = "1"
    labels {
      key         = "platform"
      value_type  = "STRING"
      description = "nfs environment"
    }
    labels {
      key         = "status_code"
      value_type  = "INT64"
      description = "status code"
    }
    labels {
      key         = "country"
      value_type  = "STRING"
      description = "country code"
    }
    labels {
      key         = "page"
      value_type  = "STRING"
      description = "page name"
    }
  }
  label_extractors = {
    "country"     = "EXTRACT(jsonPayload.country)",
    "page"        = "EXTRACT(jsonPayload.page)",
    "platform"    = "EXTRACT(jsonPayload.platform)",
    "status_code" = "EXTRACT(jsonPayload.status)"
  }
}
```

and my slo_definition is :

```
slo_definition:
  slo_name:        quality
  service_name:    nfs
  feature_name:    fr-hp
  slo_description: quality on nfs fr home page
  slo_target:      0.999
  backend:
    class:         Stackdriver
    project_id:    ${PROJECT_ID}
    method:        good_bad_ratio
    measurement:
      filter_good:
        resource.type="k8s_container"
        metric.type="logging.googleapis.com/user/nfs/quality_count"
        metric.label.page="homepage"
        metric.label.country="fr"
        metric.label.status_code=1
      filter_bad:
        resource.type="k8s_container"
        metric.type="logging.googleapis.com/user/nfs/quality_count"
        metric.label.page="homepage"
        metric.label.country="fr"
        metric.label.status_code=0
```

From [monitoring/metrics-explorer](https://console.cloud.google.com/monitoring/metrics-explorer), `filter_bad` have no results because not yet logs have `status_code=0` 

My proposition is : Why not send SLI data when one of the two filter have data ?

**Comment by benesis002** [comment]
@ocervell ;)

**Comment by benesis002** [comment]
> Sounds good to me, for `filter_bad` and `filter_good` we should continue and put the result to 0 if there is no data. For `filter_valid` however, if there is no data we can skip the computation.
> 
> To go further, there should be an option to configure how many valid records minimum `MIN_VALID_RECORDS` and skip computation if the number of results is less that this threshold. This can help in case traffic volume is very low and the SLO computation makes no sense.

If it's working already as described, we can close this issue ?

**Comment by ocervell** [comment]
It's not working as described just yet, we need to add the minimum valid records option to the SLO config and add the logic to skip computation if we have less valid results than the threshold.

**Comment by clement-pruvot** [comment]
Has this issue been fixed ?
I have a SLO where i only have bad events : when using slo-generator locally, i have a 0% SLI, but when I use it in the GCP pipeline, I have no SLI calculation.

**Comment by ocervell** [comment]
@clement-pruvot not yet, in the next minor release it will be fixed.
@bkamin29 , can you re-open this issue in the new repo https://github.com/google/slo-generator and add a link to here for context please ?
