### ISSUE TITLE
GSuite Exporter Timestamp Field

### ISSUE THREAD

**Issue by aaronsutton** [GoogleCloudPlatform/professional-services#501]
https://github.com/GoogleCloudPlatform/professional-services/blob/8f1108aecc5d19c58f6ad325d053568923c6c191/tools/gsuite-exporter/gsuite_exporter/exporters/stackdriver_exporter.py#L120

At present, the GSuite Exporter makes use of the current time when writing the events to Cloud Logging, and not the event time. While the event time is included within the `jsonPayload` field, it means that the `timestamp` field does not reflect the time that the event actually occurred.

**Comment by ocervell** [comment]
@aaronsutton can this be closed since you've fixed it ? Thanks :)

**Comment by aaronsutton** [comment]
Yes. Thanks.
