### ISSUE TITLE
ImportError: cannot import name '_load_credentials_from_file'

### ISSUE THREAD

**Issue by Puhanshibani** [GoogleCloudPlatform/professional-services#520]
i am trying to get gsuite super admin users activity using gsuite_exporter library. But i am getting error like "from google.auth._default import _load_credentials_from_file,  ImportError: cannot import name '_load_credentials_from_file'".
Can please help me out to resolve this issue.

**Comment by tsheth** [comment]
I am also getting same error.

Steps to reproduce:
1) pip install gsuite-exporter
2) execute CLI or python liberary ( gsuite-exporter  --credentials-path='D:\path\to\file\credentials.json')

Error:

 File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\Scripts\gsuite-exporter.exe\__main__.py", line 5, in <module>
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\gsuite_exporter\cli.py", line 23, in <module>
    from gsuite_exporter.collectors.reports import AdminReportsAPIFetcher
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\gsuite_exporter\collectors\reports.py", line 17, in <module>
    from gsuite_exporter import auth
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\gsuite_exporter\auth.py", line 19, in <module>
    from google.auth._default import _load_credentials_from_file

**Comment by tsheth** [comment]
I was able to fix the issue by modifying gsuite exporter authentication module  (auth.py ).

In auth.py i have changed " _load_credentials_from_file" to " load_credentials_from_file" which made import successfully work

**Comment by palladius** [comment]
Can we rename the issue [gsuite_exporter] ImportError: cannot import name '_load_credentials_from_file' ?
Context is unclear (I was looking for a similar credential issue but on another subrepo :) 

-- ricc@

**Comment by boredabdel** [comment]
This have been fixed in https://github.com/GoogleCloudPlatform/professional-services/pull/643

Closing

**Comment by ocervell** [comment]
Note: Update the `gsuite-exporter` with `pip3 install -U gsuite-exporter`
