### ISSUE TITLE
[SLO-Generator] Add a YAML/JSON validator

### ISSUE THREAD

**Issue by bkamin29** [GoogleCloudPlatform/professional-services#525]
Have a tool/function to valide the good schema of `SLO_CONFIG_FILE` and `ERROR_BUDGET_POLICY_FILE`
And use it on CICD

**Comment by ocervell** [comment]
Excellent idea ! Do you think it should run prior to the `slo-generator` (e.g a separate command `slo-generator-validate`), or should we add a step to the main command to first validate the schema before running the API calls ?

**Comment by benesis002** [comment]
> Excellent idea ! Do you think it should run prior to the `slo-generator` (e.g a separate command `slo-generator-validate`), or should we add a step to the main command to first validate the schema before running the API calls ?

We can create the function and add a new args to use it with the CLI ?
This validator feature have to be used from a CICD and before Cloud Function execution to add a error log in case of malformed config file

**Comment by ocervell** [comment]
Sounds good to me. Let's add a `--validate` flag to the CLI then and write the appropriate function.

**Comment by ocervell** [comment]
@bkamin29 can you re-open this issue in https://github.com/google/slo-generator and link to here for context ?
