### ISSUE TITLE
UnitTest failure in tools/hive-bigquery module

### ISSUE THREAD

**Issue by prathapreddy123** [GoogleCloudPlatform/professional-services#532]
Unittests inside tools/hive-bigquery/tests/test_kms_component.py is failing during creation of KeyManagementServiceClient.  Reasons for failure needs to be investigated.

**Comment by tswast** [comment]
@jaketf Do we have an owner for this tool? I don't particularly want to be "it" just because I was last to touch it.

(Also, I suspect this is due to `google-cloud-kms` 2.0 release on July 30, which has breaking changes. Temporary fix should have been to pin the dependencies, not disable the tests)

**Comment by tswast** [comment]
Filed googleapis/python-kms#37 so that we can eventually migrate to `google-cloud-kms` 2.0

**Comment by jaketf** [comment]
@roderickyao worked on this asset with a partner who's not longer working with us. I'd say he is defacto owner.

**Comment by agold-rh** [comment]
@pkattamuri @pkattamuri @tswast Do you have any input on this, or should this be closed as stale?

**Comment by tswast** [comment]
Looks like https://github.com/googleapis/python-kms/issues/37 was closed as fixed. SGTM to close this issue.
