### ISSUE TITLE
[iot-nirvana] Deployments failed : appcfg is no longer supported

### ISSUE THREAD

**Issue by startr3k** [GoogleCloudPlatform/professional-services#567]
Running mvn -pl app-engine appengine:update to deploy the app engines encountered error :

98% Application deployment failed. Message: Deployments using appcfg are no longer supported. See https://cloud.google.com/appengine/docs/deprecations
99% Rolling back the update.

**Comment by minesh1291** [comment]
I am also facing the same issue. @startr3k Please let me know if you found any workaround for this.

**Comment by pavvukk** [comment]
If anyone else if facing this issue, here are the steps that helped me resolve:
1. Add this to your pom
<plugin>
        <groupId>com.google.cloud.tools</groupId>
        <artifactId>appengine-maven-plugin</artifactId>
        <version>2.4.3</version>
      </plugin>
2. Deploy using "mvn package appengine:deploy -Dapp.deploy.projectId=$PROJECT_ID -Dapp.deploy.version=1"
That's it! Hope it helps someone
