### ISSUE TITLE
SyntaxError in gcpviz

### ISSUE THREAD

**Issue by giladsheffer** [GoogleCloudPlatform/professional-services#573]
I was trying to run gcpviz example from the documents:
`docker run --rm -v $PWD/cai:/gcpviz/cai IMAGE_ID gcpviz.sh network --query-file queries/data.js`

And getting the following error:
`Failed to create graph: SyntaxError: (anonymous): Line 103:16 Unexpected token ILLEGAL (and 2 more errors)`

To reproduce:
```
gcloud asset export --content-type=resource --output-path="gs://PATH" --project=PROJECT
# Download result to folder name cai
cd tools/gcpviz
docker build .
docker run --rm -v $PWD/cai:/gcpviz/cai IMAGE_ID gcpviz.sh network --query-file queries/data.js
```

Docker version:`Docker version 19.03.13, build 4484c46d9d`

**Comment by xtavras** [comment]
Have same problem. Basically it fails on this step:

`./gcpviz -mode visualize  --query-file queries/data.js > cai/network.gv `

Same docker image builded locally.

**Comment by rosmo** [comment]
I think the message has to do with that you don't have an organization resource in your `resource_inventory.json`. Have you done an export of the entire organization? You can check if you have the organization resource by running:

```sh
$ grep 'cloudresourcemanager.googleapis.com/Organization' resource_inventory.json | python -mjson.tool
{
    "ancestors": [
        "organizations/312281222529"
    ],
    "asset_type": "cloudresourcemanager.googleapis.com/Organization",
    "name": "//cloudresourcemanager.googleapis.com/organizations/1234567890",
    "resource": {
        "data": {
            "creationTime": "2019-09-08T12:44:26.196Z",
            "displayName": "example.com",
            "lifecycleState": "ACTIVE",
            "name": "organizations/123456789",
            "owner": {
                "directoryCustomerId": "C00000000"
            }
        },
        "discovery_document_uri": "https://cloudresourcemanager.googleapis.com/$discovery/rest?version=v1",
        "discovery_name": "Organization",
        "version": "v1"
    },
    "update_time": "2019-10-22T04:09:06.757Z"
}
```
If you want to visualize 1 project only, you could change the `queries/data.js` on line 103 from:

```
var root = g.V("{{ index .Organizations 0 }}");
```
to
````
var root = g.V("//cloudresourcemanager.googleapis.com/projects/123456789"); // change to your project number
```

**Comment by xtavras** [comment]
Hi @rosmo 
thanks for detailed answer! Yes, I've tried with project first, if I change the line as you suggest, I don't have error but the png file is kind of empty (just green 20x20 px image). Exporting the whole orga produce the same thing, I guess I don't have permissions for Organisation export since I miss "**resource**" object?

```
grep 'cloudresourcemanager.googleapis.com/Organization' resource_inventory.json | python -mjson.tool 
{
    "ancestors": [
        "organizations/1234567890"
    ],
    "asset_type": "cloudresourcemanager.googleapis.com/Organization",
    "name": "//cloudresourcemanager.googleapis.com/organizations/1234567890",
    "update_time": "2019-10-22T04:09:06.757Z"
}
```
This is the command

`gcloud asset export --organization='1234567890' --output-path='gs://somebucket'`

**Comment by rosmo** [comment]
Just add `--content-type resource` to the `gcloud asset export` command and you should get the resource objects :)

**Comment by xtavras** [comment]
Yes, that did the trick, thanks, I only now saw the glcoud example in README. Now the "dot" command runs for two no sure if it's normal. IMO the issue could be closed, but I'm not the OP.

**Comment by taneli-leppa-google** [comment]
`dot` command should not run for two hours. Are you giving it any input? I think it might be waiting for things to arrive from stdin... you maybe missing the input `.gv` file from the commandline?

**Comment by rosmo** [comment]
`dot` command should not run for two hours. Are you giving it any input? I think it might be waiting for things to arrive from stdin... you maybe missing the input `.gv` file from the commandline?

**Comment by xtavras** [comment]
I run command directly with --verbose

**Comment by xtavras** [comment]
Ok, after 'Ctrl+C'ed it take a bit and generated the graph finally, but it's really too big 32767 x 13885 pixels, I see basically every resource there, not just network. Maybe I did mistake somewhere, will try again.

**Comment by xtavras** [comment]
Ok @rosmo just ignore it, I did everything again step by step and now it's working fine, thanks again for the tool!

**Comment by rosmo** [comment]
Great! Happy to help!

**Comment by rosmo** [comment]
By the way, the DPI value controls how large images you will get. For SVG, 60 is good (and SVG is the best output!). You can override it by giving `dot -Gdpi=60` flag.

**Comment by rosmo** [comment]
@giladsheffer Were you able to solve your issue with some of the tips here?

**Comment by gilad-orca** [comment]
@rosmo Thank you very much!
Those tips helped me run it successfully :)

**Comment by giladsheffer** [comment]
@rosmo Thank you very much!
Those tips helped me run it successfully :)

**Comment by boredabdel** [comment]
Is this resolved ? can we close this or something needs to be updated in the code?

**Comment by rosmo** [comment]
@boredabdel Yes, please close it, since I can't seem to do that.
