### ISSUE TITLE
BQ Audit Log / servicedata_v1_bigquery does not exist

### ISSUE THREAD

**Issue by mycaule** [GoogleCloudPlatform/professional-services#575]
When trying to run this query into the BigQuery console, I get the following error.

https://github.com/GoogleCloudPlatform/professional-services/blob/f1fc6071d0aa31c1dbcb4b0468d0acf72ee072c9/examples/bigquery-audit-log/bigquery_audit_log.sql#L63

```
Field name servicedata_v1_bigquery does not exist in STRUCT<serviceName STRING, methodName STRING, resourceName STRING, ...> at [56:31]
```

It looks like these fields are not present in the `cloudaudit_google_apis_com_data_access_*` tables I got while running the sink.

**Comment by jaketf** [comment]
@danieldeleo could this be a v1 v.s. v2 audit logs thing? should we deprecate this asset and point to https://github.com/GoogleCloudPlatform/bigquery-utils/tree/master/views/audit ?

**Comment by TichMandivenga** [comment]
you need to change your sink to use resource.type="bigquery_resource" filter

**Comment by hemantakhandare** [comment]
> 

Thanks
