### ISSUE TITLE
Launching Dataproc Jobs with Cloud Composer example fails

### ISSUE THREAD

**Issue by bdoohan-goog** [GoogleCloudPlatform/professional-services#603]
I am using the code located here:  https://github.com/GoogleCloudPlatform/professional-services/tree/main/examples/cloud-composer-examples/composer_http_post_example 

The lab pulls from this GCS bucket (gs://spls/gsp286/professional-services .)

We set up the IAP using the directions in this CE lab (https://ce.qwiklabs.com/focuses/42671). When we run this step

```
python dag_trigger.py \
--url="${AIRFLOW_URI}/api/experimental/dags/average-speed/dag_runs" \
--iapClientId=$CLIENT_ID \
--raw_path=gs://$PROJECT/cloud-composer-lab/raw-$EXPORT_TS/
```
We get this error:

```
Invalid IAP credentials: JWT audience doesn't match this application ('aud' claim (YYYYYY.apps.googleusercontent.com) doesn't match expected value (XXXXXXX.apps.googleusercontent.com))"
```
but my client_id is "YYYYYYYYY.apps.googleusercontent.com"

I believe that this may be the issue: https://stackoverflow.com/questions/54369675/google-iap-keeps-responding-with-401-unauthorized

**Comment by boredabdel** [comment]
Hi,

This repo is maintained on a best effort basis. Is this something you can contribute on ? Otherwise i cannot garantee we will fix it and we will have to unfortunately close this

**Comment by agold-rh** [comment]
Closed due to inactivity.
