### ISSUE TITLE
asset-inventory: additional properties names are sanitized

### ISSUE THREAD

**Issue by francois-gay-lmfr** [GoogleCloudPlatform/professional-services#614]
additional properties names are sanitized before their tranformation into name/value.

Exemple in appengine services : {'20210104T104703': 1} becomes {'name': '_20210104T104703', 'value': 1}

**Comment by boredabdel** [comment]
@bmenasha Are you gonna be able to look at this?

**Comment by bmenasha** [comment]
i think this was resolved with https://github.com/GoogleCloudPlatform/professional-services/pull/613

**Comment by boredabdel** [comment]
Great thanks
