### ISSUE TITLE
Update setup guide URL

### ISSUE THREAD

**Issue by SimonSmart1** [GoogleCloudPlatform/professional-services#620]
The new location of the help article is on Partner Advantage (cloud connect no longer exists)

File is now here: https://docs.google.com/document/d/1TOSEwSD5A9iT9jTt_3aymNgRjey1wVn6-cdZH9mMorM

**Comment by rosmo** [comment]
Where exactly should this link be updated? Here?: https://github.com/GoogleCloudPlatform/professional-services/blob/main/tools/netblock-monitor/README.md

**Comment by boredabdel** [comment]
No reaction from the original author of the issue. Closing as stale.
