### ISSUE TITLE
Some features are missing in bq-visualizer

### ISSUE THREAD

**Issue by ytakaya** [GoogleCloudPlatform/professional-services#624]
I cloned the code of bq-visualizer from this repository and built the application with the following command.
```
$ cd ./tools/bq-visualizer
$ npm install
$ ng build
```
bq-visualizer also has an officially released application, and I found some feature differences between it and the application I built.
What I mean as a diff is
- "Get by Job Id" in the Select Job tab
- Check box labeled "List jobs for all users" in Select Job tab
- "Progress" tab

Maybe there are other differences.
Is there a special reason for the difference between the official apps and the build apps?
[official app](https://bqvisualiser.appspot.com/)

**Comment by boredabdel** [comment]
Hi 

tools/bq-visualizer was not updated since 2 years now. I don't have the context but i guess it was written as we didn't had an offical app that the time. Since now we do i would recommend to use the official one and treat this as deprecated. I will remove the  tool later.

**Comment by boredabdel** [comment]
@iht fyi.

**Comment by ytakaya** [comment]
I see, thanks for letting me know!
