### ISSUE TITLE
Estimated costs are way out of what the gcp billing is delivering

### ISSUE THREAD

**Issue by pmonteiro1976** [GoogleCloudPlatform/professional-services#654]
We set up this report following the instructions and we are seeing estimated costs way out of what is expected and even billed from google to us- like 80% off:
![image](https://user-images.githubusercontent.com/29040127/121199729-12f47a80-c86b-11eb-864e-f4bc12989a54.png)

**Comment by boredabdel** [comment]
Hi,

Which tool is this about?

**Comment by boredabdel** [comment]
Closing as we haven't heard anything from the reporter.

Please re-open if you think this is still an issue
