### ISSUE TITLE
direct-upload-to-gcs app engine build& deployment timeout 10 mins

### ISSUE THREAD

**Issue by jieunjeon** [GoogleCloudPlatform/professional-services#709]
From example "direct-upload-to-gcs app", I am trying to deploy the /appengine go app to App Engine, but it fails because of the 10 mins timeout for Cloud Build.

So far I've tried to update the timeout with `gcloud config`
<img width="208" alt="Screen Shot 2021-10-17 at 12 24 04 PM" src="https://user-images.githubusercontent.com/21028199/137609632-f5f1ac99-746b-4bd9-89f7-5391cff98bab.png">

but still the build fails and from the log I can see the timeout is not applied.
<img width="760" alt="Screen Shot 2021-10-17 at 12 25 54 PM" src="https://user-images.githubusercontent.com/21028199/137609671-42693df6-f14e-4dad-a619-96b47dcd5827.png">
<img width="914" alt="Screen Shot 2021-10-17 at 12 26 44 PM" src="https://user-images.githubusercontent.com/21028199/137609686-2653cb5b-f818-4bba-8773-e6a281a93362.png">

Please help me resolving this issue. Thanks.

**Comment by mingzew** [comment]
I had the same issue, Make the change referred [here](https://github.com/googleapis/google-cloud-go/issues/1359#issuecomment-480988126) for go.mod file

**Comment by boredabdel** [comment]
I upgraded the dependencies for this example and the app is deployed to appengine

https://github.com/GoogleCloudPlatform/professional-services/pull/740

please have a look
