### ISSUE TITLE
yum -y update may be more than required to satisfy prereqs

### ISSUE THREAD

**Issue by vicenteg** [GoogleCloudPlatform/professional-services#747]
https://github.com/GoogleCloudPlatform/professional-services/blob/6a9e016493fb782b73ff4771975cb56e917de177/tools/hive-bigquery/prerequisites/prerequisites.sh#L29

For apt we call `apt-get update`, and for yum based distros we call `yum -y update`, but these are not equivalent; on yum distros, this updates all packages, which seems more than is necessary to satisfy prerequisites, and it also runs for a long time. Given the use of `apt-get update`, my guess is the intent here is to refresh the package index, not to update all packages, only on yum-based systems.

Should we instead be using `yum makecache`, since this seems closer to function `apt-get update` serves, and also runs much more quickly?

**Comment by boredabdel** [comment]
You are right indeed. I will fix it.
