### ISSUE TITLE
BQ Visualizer - Not able to login

### ISSUE THREAD

**Issue by cshubham173** [GoogleCloudPlatform/professional-services#764]
I setup BQ Visualizer on a nginx webserver, I passed the clientID from Oauth Credentials. I even created a url ending with .com. I still cant login in it. It shows error 404 when i select my account on google sign in screen. Please help!

**Comment by boredabdel** [comment]
@smeyn can you have a look please ?

**Comment by cshubham173** [comment]
Hey guys, any update on this?

**Comment by boredabdel** [comment]
@cshubham173 not yet. Please keep in mind that this repo is maintained on a best effort basis we cannot garantee a reply or resolution as this is a joined effort.

Can you please share more details on the issue you are facing ? Screnshots, logs and details of your setup

**Comment by smeyn** [comment]
First of all. You don't have to host your own. You can go to https://bqvisualiser.appspot.com
Second: what is the debug console in Chrome saying? What is hte request it sends that gets the 404?

**Comment by cshubham173** [comment]
Pasting below the request fields. Redacted my org's name and IP. We even tried changing the webserver from nginx to python http, faced the same issue.

Request URL: 
<redacted>/jobs
Request Method: 
GET
Status Code: 
404 
Remote Address: 
<redacted>
Referrer Policy: 
strict-origin-when-cross-origin
Response Headers
alt-svc: 
clear
content-length: 
571
content-type: 
text/html
date: 
Tue, 15 Mar 2022 08:05:48 GMT
server: 
nginx/1.14.2
via: 
1.1 google
Request Headers
:authority: 
<redacted>
:method: 
GET
:path: 
/jobs
:scheme: 
https
accept: 
text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
accept-encoding: 
gzip, deflate, br
accept-language: 
en-GB,en-US;q=0.9,en;q=0.8
cache-control: 
max-age=0
referer: 
https://accounts.google.com/
sec-ch-ua: 
" Not A;Brand";v="99", "Chromium";v="98", "Google Chrome";v="98"
sec-ch-ua-mobile: 
?0
sec-ch-ua-platform: 
"Windows"
sec-fetch-dest: 
document
sec-fetch-mode: 
navigate
sec-fetch-site: 
cross-site
sec-fetch-user: 
?1
upgrade-insecure-requests: 
1
user-agent: 
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36

**Comment by smeyn** [comment]
The way it looks to me this happens after you complete the login dialog with the Google account server. The auth workflow will redirect back to the originating web site url. 

I see possibly two causes:
1. in the request header the  redacted :path: item does not exist. Check that the :path: is actually were the redirect is supposed to go to.
2. the :path: item is not listed in the authorised redirects in the client ID.

The client ID you configured has a number of authorized redirects. 
So when you are testing this, the URL of that host needs to be in the authorized redirects.

This is an issue with the logic of the auth login process as defined by google.

**Comment by cshubham173** [comment]
I checked the authorised redirect urls in my clientId page on GCP, it has all the correct fields
<redacted>
<redacted>/
<redacted>/jobs

We followed the instructions mentioned in the readme file. Let me know if I should try adding any more fields to the redirect urls.

**Comment by cshubham173** [comment]
Update - I got it to work!
The website hosted here https://bqvisualiser.appspot.com/ redirects to [url]/ , but the code on github when deployed, redirects to [url]/jobs and shows error 404. So there is a discrepancy there.
Fix - I edited environment.prod.ts file to redirect to '/' instead of '/jobs' and it started logging me in correctly.
