### ISSUE TITLE
Permission issue with gcloud organizations

### ISSUE THREAD

**Issue by sahajhaksh** [GoogleCloudPlatform/professional-services#856]
Hello Team,

I ran the below command 
```
gcloud organizations add-iam-policy-binding $ORG_ID --member="serviceAccount:support-slackbot@$DEVSHELL_PROJECT_ID.iam.gserviceaccount.com" --role="roles/cloudsupport.techSupportEditor";
ERROR: (gcloud.organizations.add-iam-policy-binding) User [name.surname@verve.com] does not have permission to access organizations instance [757272048914:getIamPolicy] (or it may not exist): The caller does not have permission
```
My question is can we run the same command like this instead of using ```gcloud organizations```
```
gcloud projects add-iam-policy-binding $DEVSHELL_PROJECT_ID --member="serviceAccount:support-slackbot@$DEVSHELL_PROJECT_ID.iam.gserviceaccount.com" --role="roles/cloudsupport.techSupportEditor";
```

Could someone confirm this ? This issue is related to this [Slack Integration for Google Cloud Support](https://github.com/GoogleCloudPlatform/professional-services/tree/main/tools/google-cloud-support-slackbot)

**Comment by agold-rh** [comment]
This issue should be filed on the Google Cloud CLI. 
https://cloud.google.com/support/docs/issue-trackers
