### ISSUE TITLE
examples/billboard/billboard.py - Permission Denied

### ISSUE THREAD

**Issue by lukaszsedek** [GoogleCloudPlatform/professional-services#938]
Hi, 
Created export standard and detailed billing information to bq.  Run the code from cloudshell. I have I followed the tutorial from bit.ly/billboard-template and I see an error:
`Permission Denied so you do not have project level permission or provided wrong project id, please check.`

I have roles assigned:
- Billing Administrator
- Owner
- Security Admin
- BigQuery Admin
- Organization Administrator

I tested it in two different gcp organizations and the result is the same. project_id get from PROJECT_ID env and this is the project where I run the python and where is bq with data.

set of my libs:
`cachetools==5.2.0
certifi==2022.9.24
charset-normalizer==2.1.1
colorama==0.4.6
google-api-core==2.10.2
google-auth==2.14.1
google-cloud-bigquery==3.4.0
google-cloud-bigquery-storage==2.16.2
google-cloud-billing==1.7.3
google-cloud-core==2.3.2
google-crc32c==1.5.0
google-resumable-media==2.4.0
googleapis-common-protos==1.57.0
grpc-google-iam-v1==0.12.4
grpcio==1.50.0
grpcio-status==1.50.0
idna==3.4
numpy==1.23.5
packaging==21.3
proto-plus==1.22.1
protobuf==4.21.9
pyarrow==10.0.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyparsing==3.0.9
python-dateutil==2.8.2
requests==2.28.1
rsa==4.9
six==1.16.0
urllib3==1.26.13`

**Comment by vmasilva** [comment]
Hi,

I replicated the issue. 

To solve it, you need to enable "Cloud Billing API" 

@ayapsone, I would like to suggest an improvement, to avoid this issue. 
In this block:

``
    project_id_temp = "projects/{}".format(args.PROJECT_ID)
    try:
        project_billing_info = billing.CloudBillingClient(
        ).get_project_billing_info(name=project_id_temp)
    except PermissionDenied:
        print(
            "Permission Denied so you do not have project level permission or provided wrong project id, please check."
        )
        return sys.exit(1)
``

Add a validation to check if the API is enabled, because returning "Permissions Denied" is hiding the root cause.

Thank you.

**Comment by ayapsone** [comment]
I have a new code to be pushed and will try to incorporate this.
