### ISSUE TITLE
Flag for using private IP is wrong

### ISSUE THREAD

**Issue by jiya-zhang** [GoogleCloudPlatform/professional-services#969]
In the README file, to instruct users to avoid using public IP for their job, it says:
![Screenshot 2023-01-04 at 11 02 49 AM](https://user-images.githubusercontent.com/47513414/210630442-afbaaad3-b7d5-4e38-bdc4-5c7852f301ee.png)

However, according to the [documentation](https://cloud.google.com/dataflow/docs/reference/pipeline-options#security_and_networking), the flag `--use_public_ips=false` should be `--no_use_public_ips`. Note that please check the flag documentation for Python specifically.

**Comment by agold-rh** [comment]
@jiya-zhang To which README file does this apply?

**Comment by aymanfarhat** [comment]
@jiya-zhang Thanks for flagging this. Indeed, this parameter has changed in Dataflow, I added a PR to update this detail accordingly in the project: examples/dataflow-data-generator I guess this is the project you were referring to (couldn't find usage of this parameter anywhere else. 

For future issues, please make sure to mention the tool or example folder path that you're referring to e.g. examples/your-example etc..
