### ISSUE TITLE
Linter checks are failing for examples/left-shift-validation-pre-commit-hook

### ISSUE THREAD

**Issue by AtulanZaman** [GoogleCloudPlatform/professional-services#986]
Validating ./examples/left-shift-validation-pre-commit-hook - Checking bash files

In ./examples/left-shift-validation-pre-commit-hook/setup.sh line 73:
echo $'\\nInstalling Dependencies\\n'
     ^-- SC2028: echo may not expand escape sequences. Use printf.

In ./examples/left-shift-validation-pre-commit-hook/setup.sh line 194:
            echo $'\\n'
                 ^----^ SC2028: echo may not expand escape sequences. Use printf.

In ./examples/left-shift-validation-pre-commit-hook/setup.sh line 223:
        echo $'\\n'
             ^----^ SC2028: echo may not expand escape sequences. Use printf.

In ./examples/left-shift-validation-pre-commit-hook/setup.sh line 269:
echo $'\\nDependencies installed/updated.'
     ^-- SC2028: echo may not expand escape sequences. Use printf.

In ./examples/left-shift-validation-pre-commit-hook/setup.sh line 290:
echo $'\\nConfiguration updated.'
     ^--------------------------^ SC2028: echo may not expand escape sequences. Use printf.

In ./examples/left-shift-validation-pre-commit-hook/setup.sh line 291:
echo $'\\n-----\\n'
     ^------------^ SC2028: echo may not expand escape sequences. Use printf.

In ./examples/left-shift-validation-pre-commit-hook/setup.sh line 307:
echo $'\\nUpdating pre-commit hook...'
     ^-- SC2028: echo may not expand escape sequences. Use printf.

In ./examples/left-shift-validation-pre-commit-hook/setup.sh line 319:
echo $'\\n-----\\n'
     ^------------^ SC2028: echo may not expand escape sequences. Use printf.

In ./examples/left-shift-validation-pre-commit-hook/setup.sh line 335:
echo $'\\n-----\\n'
     ^------------^ SC2028: echo may not expand escape sequences. Use printf.

In ./examples/left-shift-validation-pre-commit-hook/setup.sh line 349:
echo $'\\nFormatting'
     ^--------------^ SC2028: echo may not expand escape sequences. Use printf.

In ./examples/left-shift-validation-pre-commit-hook/setup.sh line 352:
echo $'* Ensure that the repositories/directories contain ONLY constraint and/or constraint template manifests.\\n'
     ^-- SC2028: echo may not expand escape sequences. Use printf.

In ./examples/left-shift-validation-pre-commit-hook/setup.sh line 353:
echo $'* Link DIRECTLY to folder where constraints and/or templates are located\\n'
     ^-- SC2028: echo may not expand escape sequences. Use printf.

In ./examples/left-shift-validation-pre-commit-hook/setup.sh line 356:
echo $'\\n'
     ^----^ SC2028: echo may not expand escape sequences. Use printf.

In ./examples/left-shift-validation-pre-commit-hook/setup.sh line 367:
echo $'\\n'
     ^----^ SC2028: echo may not expand escape sequences. Use printf.

In ./examples/left-shift-validation-pre-commit-hook/setup.sh line 371:
echo $'\\n'
     ^----^ SC2028: echo may not expand escape sequences. Use printf.

In ./examples/left-shift-validation-pre-commit-hook/setup.sh line 380:
    echo $'\\n'
         ^----^ SC2028: echo may not expand escape sequences. Use printf.

In ./examples/left-shift-validation-pre-commit-hook/setup.sh line 387:
    echo $'\\n-----\\n'
         ^------------^ SC2028: echo may not expand escape sequences. Use printf.

In ./examples/left-shift-validation-pre-commit-hook/setup.sh line 405:
echo $'\\nConfiguration Updated'
     ^-------------------------^ SC2028: echo may not expand escape sequences. Use printf.

For more information:
  https://www.shellcheck.net/wiki/SC2028 -- echo may not expand escape sequen...

In ./examples/left-shift-validation-pre-commit-hook/validate.sh line 115:
echo $'Step 1: Ensuring Dependencies are Installed and Properly Configured\\n'
     ^-- SC2028: echo may not expand escape sequences. Use printf.

In ./examples/left-shift-validation-pre-commit-hook/validate.sh line 121:
echo $'Dependencies installed and properly configured.\\n'
     ^-- SC2028: echo may not expand escape sequences. Use printf.

In ./examples/left-shift-validation-pre-commit-hook/validate.sh line 206:
    echo $'\\n'
         ^----^ SC2028: echo may not expand escape sequences. Use printf.

In ./examples/left-shift-validation-pre-commit-hook/validate.sh line 255:
    for yaml in $files_to_check; do
                ^-------------^ SC2128: Expanding an array without an index only gives the first element.

For more information:
  https://www.shellcheck.net/wiki/SC2128 -- Expanding an array without an ind...
  https://www.shellcheck.net/wiki/SC2028 -- echo may not expand escape sequen...
Some files need to be formatted in ./examples/left-shift-validation-pre-commit-hook - FAIL
./examples/left-shift-validation-pre-commit-hook/setup.sh ./examples/left-shift-validation-pre-commit-hook/validate.sh 
make: *** [Makefile:28: test] Error 1
ERROR
ERROR: build step 0 "gcr.io/atu1-prod-iac-core-0/make" failed: step exited with non-zero status: 2

**Comment by agold-rh** [comment]
@tdesrosi Do you mind taking a look at this?

**Comment by tdesrosi** [comment]
Sure, I'll submit a new PR with fixes soon

**Comment by tdesrosi** [comment]
Fixed in https://github.com/GoogleCloudPlatform/professional-services/pull/989

**Comment by agold-rh** [comment]
@tdesrosi Thank you!
